package com.test.xmltojson;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "age")
	private int age;

	public obj() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public obj(java.lang.String name, int age) {
		this.name = name;
		this.age = age;
	}

}